AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestFunction:
    Properties:
      CodeUri: s3://chirillc-amazon-dtc/7550404bc2320becaf774b13f5f2e26a
      Environment:
        Variables:
          S3_BUCKET: test-bucket-name
      Events:
        TestFunctionResource:
          Properties:
            Method: get
            Path: /resource/{resourceId}
          Type: Api
      Handler: index.handler
      Runtime: nodejs4.3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
